**Read CSV file**

In [6]:
import pandas as pd
data = pd.read_csv('/bigmart_data.csv')

**Review Dataset**

In [8]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [32]:
pivot = pd.pivot_table(data, index=['Item_Type'], values="Item_Weight", aggfunc= 'mean')
pivot = pivot.rename(columns = {'Item_Weight':'Mean_Weight'})
pivot

                       Mean_Weight
Item_Type
Baking Goods             12.277108
Breads                   11.346936
Breakfast                12.768202
Canned                   12.305705
Dairy                    13.426069
Frozen Foods             12.867061
Fruits and Vegetables    13.224769
Hard Drinks              11.400328
Health and Hygiene       13.142314
Household                13.384736
Meat                     12.817344
Others                   13.853285
Seafood                  12.552843
Snack Foods              12.987880
Soft Drinks              11.847460
Starchy Foods            13.690731

**Alternate Way of Summarizing Table**

In [33]:
weight_by_item = data.groupby('Item_Type')
weight_by_item.Item_Weight.mean()

Item_Type
Baking Goods             12.277108
Breads                   11.346936
Breakfast                12.768202
Canned                   12.305705
Dairy                    13.426069
Frozen Foods             12.867061
Fruits and Vegetables    13.224769
Hard Drinks              11.400328
Health and Hygiene       13.142314
Household                13.384736
Meat                     12.817344
Others                   13.853285
Seafood                  12.552843
Snack Foods              12.987880
Soft Drinks              11.847460
Starchy Foods            13.690731
Name: Item_Weight, dtype: float64

In [ ]:
data.groupby('Item_Type').Item_Weight.mean()

Item_Type
Baking Goods             12.277108
Breads                   11.346936
Breakfast                12.768202
Canned                   12.305705
Dairy                    13.426069
Frozen Foods             12.867061
Fruits and Vegetables    13.224769
Hard Drinks              11.400328
Health and Hygiene       13.142314
Household                13.384736
Meat                     12.817344
Others                   13.853285
Seafood                  12.552843
Snack Foods              12.987880
Soft Drinks              11.847460
Starchy Foods            13.690731
Name: Item_Weight, dtype: float64

In [37]:
pivot_outlet_size = pd.pivot_table(data, index=['Outlet_Size','Outlet_Type'], values='Item_MRP', aggfunc='mean')
pivot_outlet_size

                                 Item_MRP
Outlet_Size Outlet_Type
High        Supermarket Type1  141.425982
Medium      Supermarket Type1  140.297699
            Supermarket Type2  141.678634
            Supermarket Type3  139.801791
Small       Grocery Store      139.787088
            Supermarket Type1  142.589934

In [44]:
pd.crosstab(data['Outlet_Size'],data['Item_Type'], margins= False)

Item_Type,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,Fruits and Vegetables,Hard Drinks,Health and Hygiene,Household,Meat,Others,Seafood,Snack Foods,Soft Drinks,Starchy Foods
Outlet_Size,,,,,,,,,,,,,,,,
High,73,25,13,65,80,92,142,23,61,103,41,16,5,125,49,19
Medium,203,83,36,217,218,274,413,75,170,289,149,52,21,408,137,48
Small,187,71,30,189,198,249,328,50,136,257,119,55,20,335,126,38

In [46]:
average_item_visibility = data.groupby(['Item_Identifier'])['Item_Visibility'].mean().reset_index()
average_item_visibility

     Item_Identifier  Item_Visibility
0              DRA12         0.031956
1              DRA24         0.048062
2              DRA59         0.134718
3              DRB01         0.082126
4              DRB13         0.008002
...              ...              ...
1554           NCZ30         0.024956
1555           NCZ41         0.051623
1556           NCZ42         0.009044
1557           NCZ53         0.027775
1558           NCZ54         0.080426

[1559 rows x 2 columns]

In [47]:
import numpy as np

data[average_item_visibility_2] = data.groupby(['Item_Identifier'])['Item_Visibility'].transform(np.mean())

TypeError: mean() missing 1 required positional argument: 'a'

In [ ]:
data.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [ ]:
# sum of Item_MRP
data.Item_MRP.sum()

np.float64(1201681.4808)

In [ ]:
# average of Item_MRP
data.Item_MRP.mean()

np.float64(140.9927819781767)

In [ ]:
# median of Item_MRP
data.Item_MRP.median()

143.0128

In [ ]:
# mode of Outlet_type.
data.Outlet_Type.mode()

0    Supermarket Type1
Name: Outlet_Type, dtype: object

In [ ]:
# outlet_type values_count
data.Outlet_Type.value_counts()

Outlet_Type
Supermarket Type1    5577
Grocery Store        1083
Supermarket Type3     935
Supermarket Type2     928
Name: count, dtype: int64

In [ ]:
data.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [ ]:
# how to get missing values in each column.
data.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [ ]:
# Group by items
# if you find output '<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7ec664b4b7a0>' means the result is a dataframe to further access it you have to use "first()" function
data.groupby('Item_Type')

In [ ]:
x = data.groupby('Item_Type').first()
x

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Type,,,,,,,,,,,
Baking Goods,FDP36,10.395,Regular,0.000000,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
Breads,FDO23,17.850,Low Fat,0.000000,93.1436,OUT045,2002,Medium,Tier 2,Supermarket Type1,2174.5028
Breakfast,FDP49,9.000,Regular,0.069089,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1,1547.3192
Canned,FDC14,21.350,Regular,0.072222,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362
Dairy,FDA15,9.300,Low Fat,0.016047,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
Frozen Foods,FDH17,16.200,Regular,0.016687,96.9726,OUT045,2002,Small,Tier 2,Supermarket Type1,1076.5986
Fruits and Vegetables,FDX07,19.200,Regular,0.000000,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800
Hard Drinks,DRI11,11.650,Low Fat,0.034238,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
Health and Hygiene,NCB42,11.800,Low Fat,0.008596,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
Household,NCD19,8.930,Low Fat,0.000000,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
Meat,FDN15,17.500,Low Fat,0.016760,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
Others,NCN07,18.500,Low Fat,0.056816,132.1284,OUT010,1998,Small,Tier 3,Grocery Store,263.6568
Seafood,FDG33,10.395,Regular,0.139561,170.4764,OUT027,1985,Medium,Tier 3,Supermarket Type3,3435.5280
Snack Foods,FDO10,13.650,Regular,0.012741,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
Soft Drinks,DRC01,5.920,Regular,0.019278,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
Starchy Foods,FDH35,18.250,Low Fat,0.000000,164.7526,OUT045,2002,Medium,Tier 2,Supermarket Type1,4604.6728

In [ ]:
# return mean for each row of columns.
import numpy as np

x.mean(numeric_only=True)

NameError: name 'Item_Type' is not defined

In [ ]:
x.max(numeric_only=True)

Item_Weight                    21.350000
Item_Visibility                 0.139561
Item_MRP                      249.809200
Outlet_Establishment_Year    2009.000000
Item_Outlet_Sales            4604.672800
dtype: float64

## **Introduction to Seaborn**

In [ ]:
from ast import increment_lineno
import seaborn as sns
sns.set()
sns.set(style="darkgrid")

import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")
plt.rcParams['figure.figsize']=(10,10)

In [ ]:
sns_data = pd.read_csv('/content/bigmart_data.csv')
sns_data = sns_data.dropna(how='any')
sns_data['Visibility_Scaled'] = sns_data["Item_Visibility"]*100
sns_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Visibility_Scaled
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,1.604730
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,1.927822
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,1.676007
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,0.000000
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088,0.000000